apiVersion: v1
kind: Service
metadata:
  name: my-WebApp-service
spec:
  type: LoadBalancer
  ports:
   - name: "http-port"
     protocol: "TCP"
     port: 5001
  selector:
    app: my-WebApp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    my-WebApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-WebApp
  template:
    metadata:
      labels:
        app: my-WebApp
    spec:
      containers:
      - name: java-spring-web
        image: <+artifact.image>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
